language: php
php:
  - "7.1"

branches:
  only:
    - master

before_script:
  - php -v

script:
  - bash -n setup.sh
  - bash -n bin/pull-dotfiles

notifications:
  on_success: never
  on_failure: never
