language: ruby
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.2.0"
  - "2.3.0"

branches:
  only:
    - master

before_script: bash .travis/before_script.sh

script: bash .travis/script.sh

notifications:
  on_success: never
  on_failure: never