language: php
php:
  - "7.1"

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get -y install zsh

before_script:
  - php -v

script:
  - zsh -n setup.sh
  - zsh -n bin/pull-dotfiles

notifications:
  on_success: never
  on_failure: never
