language: php
php:
  - "7.1"

branches:
  only:
    - master

before_script:
  - php -v

script:
  - cd ~/
  - git clone --depth 1 https://github.com/Hiroto-K/dotfiles.git ~/dotfiles
  - cd ~/dotfiles
  - bash setup.sh
  - bash tests/test.sh

notifications:
  on_success: never
  on_failure: never
