name: dotfiles CI

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Update packages list and install zsh
              run: |
                sudo apt update -y
                sudo apt install -y zsh

            - name: Check syntax of initialize.zsh file
              run: zsh -n initialize.zsh

            - name: Check syntax of initialize script files
              run: "zsh -n ./scripts/init/*.zsh"

            - name: Check syntax of symlinks/dirs/bin-dotfiles/pull-dotfiles file
              run: zsh -n symlinks/dirs/bin-dotfiles/pull-dotfiles
